export {default as Collections } from "./Collections"
export {default as Trending } from "./Trending"
export {default as CategoryHome } from "./CategoryHome"
export {default as TopCollections } from "./TopCollections"
export {default as Artist } from "./Artist"
export {default as Works } from "./Works"